### PR TITLE
Fix printing available slash commands in Igor.lua

### PR DESCRIPTION
**Pull request by mtmiron**

### CODE REVIEW

**Comment by chrisbecke** [comment]
Hey there,
A bit more description of what that fix does would be helpful.
`print('',foo)` does look unusual but lua's print method when confronted with a list of parameters automatically tabs between then. so print('',... was intended to indent the output.
The proposed fix looks like a null-op.
If the indentation is failing in some way (looks ugly?) then print('\t'..table.contat... might be a better style, or just to drop the indentation.

**Comment by mtmiron** [comment]
Mm, point taken. All I can tell you is that when I downloaded and ran the
addon in Rift, it displayed nothing but a blank line. Try it in game.

Rift embeds Lua v5.1 -- it's possible that the behavior you're referring to
is more recent than that. Regardless, I thought it was a very important
function that you may not have caught, since obviously you tend to not need
a help blurb :)

**Comment by mtmiron** [comment]
You know what, it turns out that someone else's addon has aliased the print
function (improperly, obviously). Go ahead and deny the pull request. My
apologies for jumping to conclusions.

Good luck with the project,
Murray

**Comment by chrisbecke** [comment]
No problem at all.
Do feel free to submit another pull request if you find something else.
In fact, re-doing the line as
  print('\t'..table.concat(
is a pull request i'd accept as it fixes a addon addon interaction.

**Comment by mtmiron** [comment]
Well, since you bring it up, I believe the preferred way is:

Command.Console.Display("category", boolean, "message", boolean)

... Or some such, but I'm not at home and can't check. Most people have
multiple consoles, and specifying which output should go to is just good
procedure and whatnot.

I'm no Lua expert, but I know how difficult some things can be when you
haven't been programming for a decade. If you ever need any advice, feel
free to ask :)

**Pull request closed without merging**
